### ISSUE TITLE
The dilation in longformer

### ISSUE THREAD

**Issue by diaodeyi** [elb3k/vtn#1]
Hi ，thanks for your great work, i want know why the dilation in longformer is not supported?

**Comment by diaodeyi** [comment]
I think the code is in diagonaled_mm_tvm already , so why can we change the number to get the dilation?

**Comment by elb3k** [comment]
Hey @diaodeyi  thanks! Dilation option is there in [LongformerSelfAttention](https://github.com/elb3k/vtn/blob/18308361ae855fa609979b83343d75403fb410f5/longformer/longformer.py#L95), but I didn't add dilation as an option for Longformer (you can easily add this one). Most of my research was around linformer.
