### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by devksingh4** [elb3k/vtn#2]
Hi, 
Getting the error "TypeError: 'NoneType' object is not iterable" on the dataloader process for line 191 in `__getitem__`: 
```
imgs = list(map(lambda img: self.preprocess(img).unsqueeze(0), imgs))
```
is this a known issue? any known solutions?

**Comment by elb3k** [comment]
Are you using data loader with dataset, if it is which one?

**Comment by devksingh4** [comment]
I am using the Kinetics-400 dataset. I have modified the dataloader to use a CSV file for reading files instead of glob of video files, however, it gets the correct path and label for the videos so I don't think that is the issue. You can see that code at my fork: https://github.com/devksingh4/vtn

**Comment by elb3k** [comment]
Can you check if `imgs` is not `None` before this line?

**Comment by devksingh4** [comment]
Issue was on our end with corrupted data - closing issue.
